### ISSUE TITLE
Feature request: greater customisation

### ISSUE THREAD

**Issue by andypiper** [defnull/fediwall#12]
A few ideas:

- make the top box customisable e.g. as well as "Show top box" (or hide it), enable the contents to be specified by the administrator / config file
  - I would imagine this could be used to advertise a short URL to reach the web page, for example
- some custom CSS snippets and/or font overrides

**Comment by defnull** [comment]
Allowing HTML or CSS injection via query parameters sounds soooo wrong ;) I know that we could try sanitize it, but there are still issues with URL length limitations and lots of potential for abuse. That would also be a very power-user focused feature and hard to present in an accessible way.

I'd consider this a non-feature for now. If something can be implemented as simple config option (e.g. showing a branding logo) than that's the way to go. But if people want to customize their wall beyond the available settings, I'd suggest forking and self-hosting. Adding or changing CSS is easy enough, modifying the info bar is a bit more involved but still doable.

**Comment by andypiper** [comment]
This is fair. I might throw an extra piece into the README that clarifies that for greater customisation, forking and self-hosting is recommended.
